# Generated by Django 6.0.1 on 2026-02-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtemplate',
            name='ui_schema',
            field=models.JSONField(blank=True, default=dict, help_text='UI Schema defining form layout and widgets'),
        ),
    ]
