# Generated by Django 6.0.1 on 2026-02-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_testtemplate_ui_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtemplate',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo')], default='draft', max_length=20),
        ),
    ]
