# Generated by Django 6.0.1 on 2026-02-23 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_patient_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('duration_months', models.PositiveIntegerField(help_text='Duración en meses del tratamiento')),
                ('sessions_per_week', models.PositiveIntegerField(help_text='Cantidad de sesiones por semana')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='patients.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('completed', 'Completado'), ('cancelled', 'Cancelado'), ('rescheduled', 'Reprogramado')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notas o resumen de la sesión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('treatment_plan', models.ForeignKey(blank=True, help_text='Plan de recurrencia al que pertenece (si aplica)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.treatmentplan')),
            ],
        ),
    ]
