# Generated by Django 6.0.1 on 2026-02-23 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('realizada', 'Realizada'), ('ausente', 'Ausente'), ('cancelada', 'Cancelada')], default='pending', max_length=20)),
                ('written_notes', models.TextField(blank=True, help_text='Observaciones clínicas de la sesión')),
                ('voice_note', models.FileField(blank=True, help_text='Grabación de voz de la sesión', null=True, upload_to='voice_notes/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='appointments.appointment')),
            ],
        ),
    ]
