# Generated by Django 6.0.1 on 2026-01-31 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(help_text='Documento Nacional de Identidad', max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('obra_social', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('informe', models.TextField(help_text='Descripción de la sesión y evolución del paciente')),
                ('audio', models.FileField(blank=True, help_text='Grabación de la sesión', null=True, upload_to='audios_evoluciones/%Y/%m/%d/')),
                ('archivos_adjuntos', models.FileField(blank=True, help_text='Estudios u otros archivos', null=True, upload_to='adjuntos/%Y/%m/%d/')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to='gestion.paciente')),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
